// src/App.tsx
import './App.css';
import './Styles';
import { ImgstryEditor } from './containers/ImgstryEditor';
import { ThemeProvider } from '@rmwc/theme';
import React from 'react';

function App() {
    return (
        <ThemeProvider
            options={{
                primary: '#f2a62e',
                secondary: '#009ac0',
            }}
            className={'imgstry-container'}
        >
            <ImgstryEditor src="https://i.imgur.com/Ht8sj8f.jpg" />
        </ThemeProvider>
    );
}

export default App;

// src/App.svelte
<script>
  import Stage from "./components/Stage.svelte";
  import FilterPane from "./components/FilterPane.svelte";
  import "./App.scss";

  // private
  let imgstry;
</script>

<main class="imgstry-editor">
  <div class="imgstry-stage">
    <Stage
      src={'https://i.imgur.com/Ht8sj8f.jpg'}
      on:mount={ev => (imgstry = ev.detail.imgstry)} />
  </div>
  <div class="imgstry-filter-pane">
    {#if imgstry != null}
      <FilterPane {imgstry} />
    {:else}
      <p>Loading...</p>
    {/if}
  </div>
</main>
